- name: gather device information  
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ role_path }}/tasks/{{ ansible_network_os }}.yml"
    - "{{ role_path }}/tasks/h3c.yml"
    - "{{ role_path }}/tasks/unsupported_platform.yml"
