- hosts: localhost
  tasks:
    - community.general.read_csv:
        path: vms.csv
        key: hostname
      register: devices
    - debug:
        msg: "{{ item.key }}:
              {{ item.value.hostname }},
              {{ item.value.port }},
              {{ item.value.OS }}"
      loop: "{{ devices.dict|dict2items }}"

    - name: Here we are using Ansible add_host module to add a host to in-memory inventory
      add_host:
        name: "{{ item.value.hostname }}"
        groups: creatednodes
        ansible_port: "{{ item.value.port }}"
        ansible_user: root
        ansible_password: "123456"
      loop: "{{ devices.dict|dict2items }}"

- name: Collect Listener Port
  hosts: creatednodes
  tasks:
   - name : Ping current hosts
     command: /usr/bin/netstat -tunlp
     register: command_output
   - debug: msg="{{command_output.stdout}}"
   - debug: msg="{{inventory_hostname}}"
   - debug:
       var: ansible_port

- name: Collect ifconfig status
  hosts: creatednodes
  tasks:
   - name : Ping current hosts
     command: /usr/sbin/ifconfig
     register: command_output
   - debug: msg="{{command_output.stdout}}"
   - debug: msg="{{inventory_hostname}}"
   - debug:
       var: ansible_port


- name: Display Debug Message
  - debug:
      var: ansible_port
  - module: copy
      dest: ./hosts-OS-version.txt
      content: |
          {% for host in groups['all'] %}
          {% if hostvars[host]['ansible_facts']['distribution'] is defined %}
          {{ '%-50s' | format(host) }} {{ hostvars[host]['ansible_facts']['distribution'] }} {{ hostvars[host]['ansible_facts']['distribution_version'] }}
          {% else %}
          {{ '%-50s' | format(host) }} undefined
          {% endif %}
          {% endfor %}