- hosts: localhost
  tasks:
    - community.general.read_csv:
        path: vms.csv
        key: hostname
      register: devices
    - debug:
        msg: "{{ item.key }}:
              {{ item.value.hostname }},
              {{ item.value.port }},
              {{ item.value.network_os }}"
      loop: "{{ devices.dict|dict2items }}"

    - debug:
        var: hostvars[inventory_hostname]
    
    - debug:
        msg: 
        - '{{ lookup("env", "CISCO_USERNAME") }}'
        - '{{ lookup("env", "CISCO_PASSWORD") }}'
        - '{{ lookup("env", "H3C_USERNAME") }}'
        - '{{ lookup("env", "H3C_PASSWORD") }}'

    ansible_password: '{{ lookup("env", "CISCO_PASSWORD") }}'
    - name: Here we are using Ansible add_host module to add a host to in-memory inventory
      include_role:
        name: "roles/add_host"
      loop: "{{ devices.dict|dict2items }}"
      loop_control:
        loop_var: device

- name: Collect Listener Port
  hosts: creatednodes
  tasks:
   - name : Ping current hosts
     command: /usr/bin/netstat -tunlp
     register: command_output
   - debug: msg="{{command_output.stdout}}"
   - debug: msg="{{inventory_hostname}}"
   - debug:
       var: ansible_port

- name: Collect ifconfig status
  hosts: creatednodes
  tasks:
   - name : Ping current hosts
     command: /usr/sbin/ifconfig
     register: command_output
   - debug: msg="{{command_output.stdout}}"
   - debug: msg="{{inventory_hostname}}"
   - debug:
       var: ansible_port
